apiVersion: v1
kind: Pod
metadata:
  name: pod-with-capabilities
spec:
  containers:
  - name: app
    image: nginx
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
        drop:
        - ALL
